apiVersion: v1
kind: Secret
metadata:
  name: consumer-secret
  namespace: consumer
type: Opaque
data:
  KAFKA_SERVER_ADDRESS: bXktY2x1c3Rlci1rYWZrYS1ib290c3RyYXAua2Fma2Euc3ZjLmNsdXN0ZXIubG9jYWw6OTA5Mg==
  DB_PORT: ""
  DB_HOST: ""
  DB_USER: ""
  DB_NAME: ""
  DB_PASSWORD: ""
  DB_SSLMODE: ""

