apiVersion: v1
kind: Service
metadata:
  name: consumer-app-service
  namespace: consumer-app
  annotations:
    prometheus.io/scrape: 'true'
spec:
  selector:
    app: consumer-app
  ports:
    - name: http-port
      protocol: TCP
      port: 4002
      targetPort: 4002
    - name: kafka-port
      protocol: TCP
      port: 9092
      targetPort: 9092
  type: ClusterIP
