apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-app-deployment
  namespace: consumer-app
  labels:
    app: consumer-app
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: consumer-app
  template:
    metadata:
      labels:
        app: consumer-app
    spec:
      containers:
      - name: consumer-app
        image: joesam007/consumer:edge
        imagePullPolicy: Always
        ports:
        - containerPort: 4002
        - containerPort: 9092
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "200m"
            memory: "200Mi"
        env:
        - name: KAFKA_SERVER_ADDRESS
          valueFrom:
            secretKeyRef:
              name: consumer-secret
              key: KAFKA_SERVER_ADDRESS
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: consumer-secret
              key: DB_PORT
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: consumer-secret
              key: DB_USER
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: consumer-secret
              key: DB_HOST
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: consumer-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: consumer-secret
              key: DB_NAME
        - name: DB_SSLMODE
          valueFrom:
            secretKeyRef:
              name: consumer-secret
              key: DB_SSLMODE 
        livenessProbe:
          httpGet:
            path: /healthz
            port: 4002
          initialDelaySeconds: 15
          timeoutSeconds: 2
