apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: consumer-app-monitor
  namespace: consumer-app
spec:
  selector:
    matchLabels:
      app: consumer-app
  endpoints:
  - port: http-port
    interval: 30s
    path: /metrics
