apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server-deployment
  namespace: temp-app
  labels:
    app: go-server
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: go-server
  template:
    metadata:
      labels:
        app: go-server
    spec:
      containers:
      - name: go-server
        image: joesam007/temp-scraper:edge
        ports:
        - containerPort: 4000
        - containerPort: 9092
        env:
        - name: KAFKA_SERVER_ADDRESS
          valueFrom:
            secretKeyRef:
              name: kafka-secret
              key: KAFKA_SERVER_ADDRESS
        livenessProbe:
          httpGet:
            path: /healthz
            port: 4000
          initialDelaySeconds: 15
          timeoutSeconds: 2

