apiVersion: apps/v1
kind: Deployment
metadata:
  name: temp-app-deployment
  namespace: temp-app
  labels:
    app: go-server
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: temp-app
  template:
    metadata:
      labels:
        app: temp-app
    spec:
      containers:
      - name: temp-app
        image: joesam007/temp-scraper:edge
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
        - containerPort: 9092
        env:
        - name: KAFKA_SERVER_ADDRESS
          valueFrom:
            secretKeyRef:
              name: kafka-secret
              key: KAFKA_SERVER_ADDRESS

