apiVersion: v1
kind: Secret
metadata:
  name: kafka-secret
  namespace: temp-app
type: Opaque
data:
  KAFKA_SERVER_ADDRESS: <base64-encoded-value>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server-deployment
  namespace: temp-app
  labels:
    app: go-server
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: go-server
  template:
    metadata:
      labels:
        app: go-server
    spec:
      containers:
      - name: go-server
        image: joesam007/temp-scraper:edge
        ports:
        - containerPort: 8080
        - containerPort: 9092
        env:
        - name: KAFKA_SERVER_ADDRESS
          valueFrom:
            secretKeyRef:
              name: kafka-secret
              key: KAFKA_SERVER_ADDRESS
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 2

---
apiVersion: v1
kind: Service
metadata:
  name: go-server-service
  namespace: temp-app
spec:
  selector:
    app: go-server
  ports:
    - name: http-port
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
    - name: kafka-port
      protocol: TCP
      port: 9092
      targetPort: 9092
      nodePort: 30092
  type: NodePort
