apiVersion: v1
kind: Secret
metadata:
  name: kafka-secret
  namespace: temp-app
type: Opaque
data:
  KAFKA_SERVER_ADDRESS: bXktY2x1c3Rlci1rYWZrYS1ib290c3RyYXAua2Fma2Euc3ZjLmNsdXN0ZXIubG9jYWw6OTA5Mg==
