apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack-chart
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 56.6.0
    helm:
      values: |
        serviceMonitorNamespaceSelector: {}


  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true