apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipfs
  namespace: ipfs
  labels:
    name: ipfs
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ipfs
    spec:
      containers:
      - name: ipfs
        image: "ipfs/go-ipfs:v0.12.2"
        ports:
        - containerPort: 4001
          name: "swarm"
          protocol: "TCP"
        - containerPort: 5001
          name: "api"
          protocol: "TCP"
        - containerPort: 8080
          name: "gateway"
          protocol: "TCP"

---
apiVersion: v1
kind: Service
metadata:
  name: ipfs
  namespace: ipfs
spec:
  type: NodePort
  ports:
  - name: ipfs
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: ipfs
