apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipfs
  namespace: ipfs
  labels:
    app: ipfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ipfs
  template:
    metadata:
      labels:
        app: ipfs
    spec:
      containers:
      - name: ipfs
        image: "ipfs/go-ipfs:v0.12.2"
        ports:
        - containerPort: 4001
          name: "swarm"
          protocol: "TCP"
        - containerPort: 5001
          name: "api"
          protocol: "TCP"
        - containerPort: 8080
          name: "gateway"
          protocol: "TCP"
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            memory: "712Mi"
            cpu: "700m"
        volumeMounts:
        - name: ipfs-data
          mountPath: /data/ipfs
      volumes:
      - name: ipfs-data
        emptyDir: {}


---
apiVersion: v1
kind: Service
metadata:
  name: ipfs
  namespace: ipfs
spec:
  type: NodePort
  ports:
  - name: gateway
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: api
    port: 5001
    targetPort: 5001
  - name: swarm
    port: 4001
    targetPort: 4001
    protocol: TCP
  selector:
    app: ipfs
