apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ipfs-monitor
  namespace: ipfs
  labels:
    release: prometheus-stack-chart
spec:
  selector:
    matchLabels:
      app: ipfs
  endpoints:
  - port: gateway
    interval: 30s
  - port: api
    interval: 30s